# This file enables the "Sponsor" button on your repo
# It points to your personal GitHub Sponsors page.
github: [NaimGQKC]

# When you set up other platforms, you can add them here:
# open_collective: nfp-influencers
# custom: ['https://www.buymeacoffee.com/your-project-link']